name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    env:
      DEVICE: "iPhone 11"
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: set -o pipefail && xcodebuild clean -destination "platform=iOS Simulator,name=$DEVICE" build-for-testing | xcpretty --color --simple
    - name: Run tests
      run: set -o pipefail && xcodebuild test-without-building -xctestrun $(find . -type f -name "*.xctestrun") -destination "platform=iOS Simulator,name=$DEVICE" -enableCodeCoverage YES | xcpretty --color --simple
